// NUR Fleet Master Registry // 36 Civilizational Ships (18 Sovereign Conservative + 18 Liberal Sky Yachts across 18 Civilizations)

export type ShipFaction = "conservative" | "liberal";
export type ShipType = "wing" | "gothic" | "dome" | "pagoda" | "torii" | "vimana" | "yacht" | "neon_cube" | "citadel" | "bamboo" | "temple" | "barge";
export type DefenseAlliance = "NATO" | "SCO_BRICS" | "QUAD_PACIFIC" | "GCC_ARAB" | "AU_AFRICA" | "LATAM_MERCOSUR" | "ASEAN_PACIFIC";

export interface CivilizationalShip {
  id: string;
  name: string;
  faction: ShipFaction;
  shipType: ShipType;
  alliance: DefenseAlliance;
  allianceName: string;
  civilization: string;
  civilizationKey: string;
  architecture: string;
  anchors: string[];
  theme: string;
  targetRegion: string;
  primaryMission: string;
  terminalUrl: string;
  hullColor: string;
  accentColor: string;
  marketIndex: string;
  marketIndexName: string;
  primarySymbol: string;
  orbitalCoordinates: {
    lat: number;
    lon: number;
    altitudeKm: number;
    speed: number;
  };
  telemetry: {
    reactorCore: string;
    shieldStatus: number;
    warpDriveTier: string;
    quantumEntropy: number;
  };
}

export const CIVILIZATIONAL_FLEET: CivilizationalShip[] = [
  // ──────────────────────────────────────────────────────────
  // 18 SOVEREIGN CONSERVATIVE DREADNOUGHTS (STATE DOCTRINE & SACRED ARCHIVES)
  // ──────────────────────────────────────────────────────────
  {
    id: "TR_SOV",
    name: "NUR-08 BOZKURT TİTANI",
    faction: "conservative",
    shipType: "wing",
    alliance: "NATO",
    allianceName: "🔵 NATO DOĞU KANADI // TÜRK EGEMENLİK DOKTRİNİ",
    civilization: "Turkish Sovereign",
    civilizationKey: "turkish",
    architecture: "Selçuklu Çift Başlı Kartal & Bozkurt Titanyum Pruva, Samsunspor Kırmızı-Beyaz-Siyah",
    anchors: ["Kaan Selçuk Demir", "Elif Nur Erdem"],
    theme: "Resmi Devlet Aklı, Osmanlı/Selçuklu Mirası & 19 Mayıs Ruhu",
    targetRegion: "Ankara / Doğu Akdeniz / Samsun",
    primaryMission: "Türk Dünyası & NATO Doğu Kanadı Güvenlik Devriyesi",
    terminalUrl: "/NUR_FINANS_CAPTAIN_TERMINAL.html",
    hullColor: "#0a0a0f",
    accentColor: "#dc2626",
    marketIndex: "BIST 100",
    marketIndexName: "Borsa İstanbul Ulusal 100",
    primarySymbol: "ASELS.IS",
    orbitalCoordinates: { lat: 39.9, lon: 32.8, altitudeKm: 418.55, speed: 0.0038 },
    telemetry: { reactorCore: "Seljuk Dark-Matter Fusion 9.2 GW", shieldStatus: 99.4, warpDriveTier: "Warp 9.8", quantumEntropy: 0.0014 }
  },
  {
    id: "UK_SOV",
    name: "TUDOR VANGUARD (MAJESTIC)",
    faction: "conservative",
    shipType: "gothic",
    alliance: "NATO",
    allianceName: "🔵 NATO SACLANT KUZEY ATLANTİK",
    civilization: "British / US Sovereign",
    civilizationKey: "anglo",
    architecture: "Westminster Gotik Kuleleri & Radcliffe Kubbesi Kraliyet Zırhı",
    anchors: ["Marcus Sterling", "Elena Vance"],
    theme: "Kraliyet Titanyum Zırhı & City of London Klasik Finans Doktrini",
    targetRegion: "Londra / Kuzey Atlantik",
    primaryMission: "Kuzey Atlantik Filo Savunması & Stratejik Sermaye",
    terminalUrl: "/TUDOR_FINANCE_ENGLISH_TERMINAL.html",
    hullColor: "#0f172a",
    accentColor: "#1e3a8a",
    marketIndex: "FTSE 100",
    marketIndexName: "London Stock Exchange FTSE 100",
    primarySymbol: "BP.L",
    orbitalCoordinates: { lat: 51.5, lon: -0.1, altitudeKm: 420.0, speed: 0.0035 },
    telemetry: { reactorCore: "Rolls-Royce Quantum Fission 8.8 GW", shieldStatus: 98.7, warpDriveTier: "Warp 9.6", quantumEntropy: 0.0021 }
  },
  {
    id: "DE_SOV",
    name: "WALKÜRE IMPERIAL DREADNOUGHT",
    faction: "conservative",
    shipType: "citadel",
    alliance: "NATO",
    allianceName: "🔵 NATO ORTA AVRUPA // BUNDESWEHR COMMAND",
    civilization: "German Sovereign",
    civilizationKey: "german",
    architecture: "Prusya Çelik Zırhı & Brandenburg Granit Kaplama",
    anchors: ["Heinrich von Berg", "Greta Lindemann"],
    theme: "Hanseatic Disiplin, Prusya Devlet Geleneği & Ağır Sanayi",
    targetRegion: "Berlin / Frankfurt",
    primaryMission: "Avrupa Ağır Sanayi & Merkez Bankası Kalkanı",
    terminalUrl: "/WALKURE_FINANCE_GERMAN_TERMINAL.html",
    hullColor: "#111827",
    accentColor: "#4b5563",
    marketIndex: "DAX 40",
    marketIndexName: "Frankfurt Börse DAX Performance Index",
    primarySymbol: "SAP.DE",
    orbitalCoordinates: { lat: 52.5, lon: 13.4, altitudeKm: 419.2, speed: 0.0036 },
    telemetry: { reactorCore: "Siemens Tachyon Fusion 9.5 GW", shieldStatus: 99.8, warpDriveTier: "Warp 9.7", quantumEntropy: 0.0009 }
  },
  {
    id: "CN_SOV",
    name: "TANG CELESTIAL DRAGON",
    faction: "conservative",
    shipType: "pagoda",
    alliance: "SCO_BRICS",
    allianceName: "🔴 SCO / BRICS+ AVRASYA BLOKU",
    civilization: "Chinese Sovereign",
    civilizationKey: "chinese",
    architecture: "Yasak Şehir Kademeli Pagoda & Dunhuang Solar Kanat",
    anchors: ["Chen Weilin", "Lin Xiaoyu"],
    theme: "Han Hanedanı Devlet Doktrini & Kuşak-Yol Enerji Aklı",
    targetRegion: "Pekin / Avrasya",
    primaryMission: "İpek Yolu & Avrasya Ticaret Koridoru Koruması",
    terminalUrl: "/TANG_CAPITAL_CHINESE_TERMINAL.html",
    hullColor: "#1c1917",
    accentColor: "#b91c1c",
    marketIndex: "SSE Composite",
    marketIndexName: "Shanghai Stock Exchange Index",
    primarySymbol: "601857.SS",
    orbitalCoordinates: { lat: 39.9, lon: 116.4, altitudeKm: 415.0, speed: 0.0036 },
    telemetry: { reactorCore: "Celestial Dragon Tokamak 10.1 GW", shieldStatus: 99.1, warpDriveTier: "Warp 9.9", quantumEntropy: 0.0011 }
  },
  {
    id: "JP_SOV",
    name: "TOKUGAWA KURO SHOGUN",
    faction: "conservative",
    shipType: "torii",
    alliance: "QUAD_PACIFIC",
    allianceName: "🟠 QUAD PASİFİK GÜVENLİK DİYALOĞU",
    civilization: "Japanese Sovereign",
    civilizationKey: "japanese",
    architecture: "Himeji Beyaz Balıkçıl Köşkü & Shinto Torii İticileri",
    anchors: ["Kenjiro Takahashi", "Aoi Morimoto"],
    theme: "Samuray Disiplini & İmparatorluk Geleneği",
    targetRegion: "Tokyo / Pasifik Kalkanı",
    primaryMission: "Pasifik Güvenlik & Teknoloji Kalkanı",
    terminalUrl: "/TOKUGAWA_MARKETS_JAPANESE_TERMINAL.html",
    hullColor: "#09090b",
    accentColor: "#18181b",
    marketIndex: "Nikkei 225",
    marketIndexName: "Tokyo Stock Exchange Nikkei 225",
    primarySymbol: "6758.T",
    orbitalCoordinates: { lat: 35.6, lon: 139.6, altitudeKm: 422.0, speed: 0.0037 },
    telemetry: { reactorCore: "Shinto Harmonic Quantum Drive 8.9 GW", shieldStatus: 98.9, warpDriveTier: "Warp 9.7", quantumEntropy: 0.0016 }
  },
  {
    id: "FR_SOV",
    name: "BOURBON FLEUR-DE-LIS",
    faction: "conservative",
    shipType: "gothic",
    alliance: "NATO",
    allianceName: "🔵 NATO / AB STRATEJİK OTONOMİ",
    civilization: "French Sovereign",
    civilizationKey: "french",
    architecture: "Versailles Titanyum Zırhı & Kraliyet Laciverti",
    anchors: ["Antoine de Saint-Germain", "Camille Laurent"],
    theme: "Aydınlanma Ruhu & Fransız Devlet Geleneği",
    targetRegion: "Paris / Batı Avrupa",
    primaryMission: "Avrupa Stratejik Otonomi Savunması",
    terminalUrl: "/BOURBON_ANALYTICS_FRENCH_TERMINAL.html",
    hullColor: "#030712",
    accentColor: "#1d4ed8",
    marketIndex: "CAC 40",
    marketIndexName: "Euronext Paris CAC 40",
    primarySymbol: "MC.PA",
    orbitalCoordinates: { lat: 48.8, lon: 2.3, altitudeKm: 417.0, speed: 0.0034 },
    telemetry: { reactorCore: "Areva Sub-atomic Breeder 8.7 GW", shieldStatus: 97.9, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0019 }
  },
  {
    id: "AR_SOV",
    name: "ABBASID HOUSE OF WISDOM",
    faction: "conservative",
    shipType: "dome",
    alliance: "GCC_ARAB",
    allianceName: "🟢 GCC KÖRFEZ İŞBİRLİĞİ KONSEYİ",
    civilization: "Arab Sovereign",
    civilizationKey: "arab",
    architecture: "Samarra Sarmal Minare Yerçekimi & Elhamra Mukarnas Kalkanı",
    anchors: ["Tariq Al-Mansoor", "Noor Al-Hassan"],
    theme: "Beytü'l-Hikme Bilgeliği & Hilafet Mirası",
    targetRegion: "Riyad / Basra Körfezi",
    primaryMission: "Körfez Enerji Koridoru Güvenliği",
    terminalUrl: "/ABBASID_FINANCIAL_ARABIC_TERMINAL.html",
    hullColor: "#064e3b",
    accentColor: "#047857",
    marketIndex: "TASI",
    marketIndexName: "Tadawul All Share Index",
    primarySymbol: "2222.SR",
    orbitalCoordinates: { lat: 24.7, lon: 46.6, altitudeKm: 419.0, speed: 0.0039 },
    telemetry: { reactorCore: "Solar-Plasma Stellar Core 9.4 GW", shieldStatus: 99.0, warpDriveTier: "Warp 9.8", quantumEntropy: 0.0012 }
  },
  {
    id: "IR_SOV",
    name: "PERSEPOLIS SOLAR FIRE",
    faction: "conservative",
    shipType: "citadel",
    alliance: "SCO_BRICS",
    allianceName: "🔴 SCO / BRICS+ ORTA DOĞU KANADI",
    civilization: "Persian Sovereign",
    civilizationKey: "persian",
    architecture: "Ahameniş Kanatlı Boğa Kalkanı & Zerdüşt Ateş Kulesi",
    anchors: ["Kourosh Rostami", "Shirin Afshar"],
    theme: "Büyük Kiros Silindiri, Adalet Doktrini & Avrasya Ticareti",
    targetRegion: "Tahran / İsfahan / Hürmüz",
    primaryMission: "Hürmüz Boğazı & İpek Yolu Güney Güvenliği",
    terminalUrl: "/PERSEPOLIS_CAPITAL_PERSIAN_TERMINAL.html",
    hullColor: "#292524",
    accentColor: "#b45309",
    marketIndex: "TEDPIX",
    marketIndexName: "Tehran Stock Exchange All-Share Index",
    primarySymbol: "IRO1FOLD0001",
    orbitalCoordinates: { lat: 35.7, lon: 51.4, altitudeKm: 418.8, speed: 0.0036 },
    telemetry: { reactorCore: "Zoroastrian Plasma Arc 8.6 GW", shieldStatus: 98.4, warpDriveTier: "Warp 9.6", quantumEntropy: 0.0022 }
  },
  {
    id: "RU_SOV",
    name: "RURIK SLAVIC CITADEL",
    faction: "conservative",
    shipType: "citadel",
    alliance: "SCO_BRICS",
    allianceName: "🔴 SCO / BRICS+ KUZEY KORİDORU",
    civilization: "Russian Sovereign",
    civilizationKey: "russian",
    architecture: "Aziz Vasil Kubbe Reaktörleri & Kremlin Titanyum Suru",
    anchors: ["Viktor Morozov", "Daria Volkova"],
    theme: "Üçüncü Roma & Slav Jeopolitik Aklı",
    targetRegion: "Moskova / Arktik",
    primaryMission: "Kuzey Deniz Rotası & Arktik Savunma",
    terminalUrl: "/RURIK_CAPITAL_RUSSIAN_TERMINAL.html",
    hullColor: "#18181b",
    accentColor: "#991b1b",
    marketIndex: "MOEX",
    marketIndexName: "Moscow Exchange Index",
    primarySymbol: "GAZP.ME",
    orbitalCoordinates: { lat: 55.7, lon: 37.6, altitudeKm: 421.0, speed: 0.0033 },
    telemetry: { reactorCore: "Siberian Cryo-Neutron Drive 9.6 GW", shieldStatus: 99.5, warpDriveTier: "Warp 9.7", quantumEntropy: 0.0010 }
  },
  {
    id: "IN_SOV",
    name: "MAURYA ASHOKA VIMANA",
    faction: "conservative",
    shipType: "vimana",
    alliance: "SCO_BRICS",
    allianceName: "🔴 BRICS+ / HİNT OKYANUSU İTTİFAKI",
    civilization: "Indian Sovereign",
    civilizationKey: "indian",
    architecture: "Brihadisvara Kuleleri & Konark Güneş Jiroskopu",
    anchors: ["Aarav Sharma", "Priya Iyer"],
    theme: "Dharma Çarkı & Kadim Hint Doktrini",
    targetRegion: "Yeni Delhi / Hint Okyanusu",
    primaryMission: "Güneş Çarkı Savunması",
    terminalUrl: "/MAURYA_INTELLIGENCE_HINDI_TERMINAL.html",
    hullColor: "#431407",
    accentColor: "#c2410c",
    marketIndex: "NIFTY 50",
    marketIndexName: "National Stock Exchange of India",
    primarySymbol: "RELIANCE.NS",
    orbitalCoordinates: { lat: 28.6, lon: 77.2, altitudeKm: 416.0, speed: 0.0035 },
    telemetry: { reactorCore: "Vedic Antimatter Crucible 9.3 GW", shieldStatus: 98.8, warpDriveTier: "Warp 9.7", quantumEntropy: 0.0017 }
  },
  {
    id: "ES_SOV",
    name: "HABSBURGO SAGRADA GALLEON",
    faction: "conservative",
    shipType: "gothic",
    alliance: "NATO",
    allianceName: "🔵 NATO GÜNEY KANADI // İBERYA",
    civilization: "Spanish / Hispanic Sovereign",
    civilizationKey: "spanish",
    architecture: "Sagrada Família Biyomimetik Kuleleri & Ağır Kalyon",
    anchors: ["Santiago De La Vega", "Valentina Morales"],
    theme: "İspanyol İmparatorluğu & Barok Zırh",
    targetRegion: "Madrid / Cebelitarık",
    primaryMission: "İberya & Atlantik Geçidi Kontrolü",
    terminalUrl: "/HABSBURGO_CAPITAL_SPANISH_TERMINAL.html",
    hullColor: "#1c1917",
    accentColor: "#854d0e",
    marketIndex: "IBEX 35",
    marketIndexName: "Bolsa de Madrid IBEX 35",
    primarySymbol: "SAN.MC",
    orbitalCoordinates: { lat: 40.4, lon: -3.7, altitudeKm: 418.0, speed: 0.0036 },
    telemetry: { reactorCore: "Castilian Solar Fusion 8.5 GW", shieldStatus: 98.0, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0020 }
  },
  {
    id: "IT_SOV",
    name: "NOVA ROMA CAESAR DREADNOUGHT",
    faction: "conservative",
    shipType: "citadel",
    alliance: "NATO",
    allianceName: "🔵 NATO GÜNEY KANADI // AKDENİZ",
    civilization: "Italian / Roman Sovereign",
    civilizationKey: "roman",
    architecture: "Kolezyum Mermer-Karbon Suru & Pantheon Kubbe Reaktörü",
    anchors: ["Marco Aurelio Conti", "Giulia Bellini"],
    theme: "Pax Romana Hukuk Aklı, Rönesans Bankacılığı & Akdeniz Filosu",
    targetRegion: "Roma / Milano / Akdeniz",
    primaryMission: "Akdeniz Ticaret Yolu & Kültür Mirası Muhafazası",
    terminalUrl: "/NOVA_ROMA_ITALIAN_TERMINAL.html",
    hullColor: "#18181b",
    accentColor: "#a16207",
    marketIndex: "FTSE MIB",
    marketIndexName: "Borsa Italiana FTSE MIB Index",
    primarySymbol: "ENI.MI",
    orbitalCoordinates: { lat: 41.9, lon: 12.5, altitudeKm: 417.8, speed: 0.0035 },
    telemetry: { reactorCore: "Capitoline Positron Cell 8.8 GW", shieldStatus: 98.6, warpDriveTier: "Warp 9.6", quantumEntropy: 0.0018 }
  },
  {
    id: "SE_SOV",
    name: "VALKYRIE ARCTIC BASTION",
    faction: "conservative",
    shipType: "wing",
    alliance: "NATO",
    allianceName: "🔵 NATO KUZEY KUTBU KANADI",
    civilization: "Nordic Sovereign",
    civilizationKey: "nordic",
    architecture: "Viking Drakkar Titanyum Kanatları & Fiyort Kalkanı",
    anchors: ["Astrid Lindqvist", "Lars Holmberg"],
    theme: "Kuzey Disiplini, Devlet Fonu Güvencesi & Yeşil Teknoloji",
    targetRegion: "Stockholm / Oslo / Arktik",
    primaryMission: "Kuzey Buz Denizi & Stratejik Maden Güvenliği",
    terminalUrl: "/VALKYRIE_ARCTIC_NORDIC_TERMINAL.html",
    hullColor: "#022c22",
    accentColor: "#059669",
    marketIndex: "OMX 30",
    marketIndexName: "Nasdaq Stockholm OMX 30",
    primarySymbol: "VOLV-B.ST",
    orbitalCoordinates: { lat: 59.3, lon: 18.0, altitudeKm: 422.5, speed: 0.0034 },
    telemetry: { reactorCore: "Nordic Geothermal Quantum Dynamo 9.1 GW", shieldStatus: 99.2, warpDriveTier: "Warp 9.7", quantumEntropy: 0.0013 }
  },
  {
    id: "AF_SOV",
    name: "KILWA GREAT ZIMBABWE",
    faction: "conservative",
    shipType: "bamboo",
    alliance: "AU_AFRICA",
    allianceName: "🟡 AFRİKA BİRLİĞİ (AU) BARIŞ GÜCÜ",
    civilization: "Pan-African Sovereign",
    civilizationKey: "african",
    architecture: "Lalibela Yekpare Kaya & Timbuktu Kütüphane Kulesi",
    anchors: ["Kwame Osei", "Zuri Mwangi"],
    theme: "Pan-Afrika Birliği & Kadim Krallıklar",
    targetRegion: "Addis Ababa / Rift Vadisi",
    primaryMission: "Afrika Kaynak Güvenliği & Birlik",
    terminalUrl: "/KILWA_MARKETS_AFRICAN_TERMINAL.html",
    hullColor: "#292524",
    accentColor: "#a16207",
    marketIndex: "JSE Top 40",
    marketIndexName: "Johannesburg Stock Exchange Top 40",
    primarySymbol: "NPN.JO",
    orbitalCoordinates: { lat: -1.2, lon: 36.8, altitudeKm: 423.0, speed: 0.0037 },
    telemetry: { reactorCore: "Kilwa Mineral-Pulse Core 8.9 GW", shieldStatus: 98.5, warpDriveTier: "Warp 9.6", quantumEntropy: 0.0019 }
  },
  {
    id: "LA_SOV",
    name: "AZTEC SOLAR TEMPLE",
    faction: "conservative",
    shipType: "temple",
    alliance: "LATAM_MERCOSUR",
    allianceName: "🟣 MERCOSUR & LATİN EGEMENLİK İTTİFAKI",
    civilization: "Latin American Sovereign",
    civilizationKey: "latin",
    architecture: "Teotihuacan Güneş Piramidi Basamakları & Obsidiyen Zırh",
    anchors: ["Emiliano Hernandez", "Sofia Cruz"],
    theme: "And Dağları Madencilik Gücü & Kadim İnka-Aztek Mirası",
    targetRegion: "Mexico City / Bogota / Lima",
    primaryMission: "Lityum Üçgeni & Amazon Biyo-Kaynak Kalkanı",
    terminalUrl: "/AZTEC_SOLAR_LATIN_TERMINAL.html",
    hullColor: "#3b0764",
    accentColor: "#9333ea",
    marketIndex: "B3 IBOVESPA",
    marketIndexName: "Brasil Bolsa Balcão Index",
    primarySymbol: "VALE3.SA",
    orbitalCoordinates: { lat: 19.4, lon: -99.1, altitudeKm: 419.6, speed: 0.0038 },
    telemetry: { reactorCore: "Obsidian Solar Resonator 8.7 GW", shieldStatus: 98.3, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0024 }
  },
  {
    id: "KR_SOV",
    name: "GORYEO TURTLE FLAGSHIP",
    faction: "conservative",
    shipType: "citadel",
    alliance: "QUAD_PACIFIC",
    allianceName: "🟠 DOĞU ASYA PASİFİK KALKANI",
    civilization: "Korean Sovereign",
    civilizationKey: "korean",
    architecture: "Amiral Yi Sun-sin Kaplumbağa Gemisi Çivili Zırhı & Gyeongbokgung Çatısı",
    anchors: ["Min-jun Park", "Ji-won Kim"],
    theme: "Joseon Hanedanı Stratejisi, Yarı İletken Egemenliği & Ağır Çelik",
    targetRegion: "Seul / Busan",
    primaryMission: "Kore Yarımadası & Yarı İletken Tedarik Hattı Güvenliği",
    terminalUrl: "/GORYEO_SOVEREIGN_KOREAN_TERMINAL.html",
    hullColor: "#0f172a",
    accentColor: "#0284c7",
    marketIndex: "KOSPI 200",
    marketIndexName: "Korea Composite Stock Price Index",
    primarySymbol: "005930.KS",
    orbitalCoordinates: { lat: 37.5, lon: 126.9, altitudeKm: 421.3, speed: 0.0037 },
    telemetry: { reactorCore: "Superconductor Tokamak 9.8 GW", shieldStatus: 99.4, warpDriveTier: "Warp 9.8", quantumEntropy: 0.0008 }
  },
  {
    id: "SEA_SOV",
    name: "AYUTTHAYA GOLDEN BARGE",
    faction: "conservative",
    shipType: "barge",
    alliance: "ASEAN_PACIFIC",
    allianceName: "🟤 ASEAN GÜVENLİK DİYALOĞU",
    civilization: "Southeast Asian Sovereign",
    civilizationKey: "southeast_asian",
    architecture: "Kraliyet Altın Suhuza & Malakka Boğazı Fener Reaktörü",
    anchors: ["Somchai Prasert", "Ratana Siri"],
    theme: "Siam Krallığı, Malakka Boğazı Deniz Ticareti & Baharat Rotası",
    targetRegion: "Bangkok / Singapur / Cakarta",
    primaryMission: "Malakka Boğazı Küresel Enerji Akışı Denetimi",
    terminalUrl: "/AYUTTHAYA_GOLDEN_SEA_TERMINAL.html",
    hullColor: "#451a03",
    accentColor: "#d97706",
    marketIndex: "SET 50",
    marketIndexName: "Stock Exchange of Thailand Index",
    primarySymbol: "PTT.BK",
    orbitalCoordinates: { lat: 13.7, lon: 100.5, altitudeKm: 418.2, speed: 0.0039 },
    telemetry: { reactorCore: "Golden Lotus Fusion Drive 8.6 GW", shieldStatus: 98.1, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0023 }
  },
  {
    id: "TT_SOV",
    name: "TATAR ALTIN ORDA KERVAN",
    faction: "conservative",
    shipType: "citadel",
    alliance: "SCO_BRICS",
    allianceName: "🔴 AVRASYA BOZKIR EGEMENLİK BLOKU",
    civilization: "Tatar / Eurasian Sovereign",
    civilizationKey: "tatar",
    architecture: "Kazan Kul Şerif Kubbesi & Bozkır Ak Çadır Zırhı",
    anchors: ["Ramil Nurullin", "Guzel Bikbulatova"],
    theme: "İdil-Ural Ticaret Aklı, Altın Orda Mirası & Avrasya Kripto-Takas",
    targetRegion: "Kazan / İdil Boyu / Ufa",
    primaryMission: "Kuzey-Güney Avrasya Ticaret Koridoru & Enerji Takası",
    terminalUrl: "/TATAR_FINANS_CAPITAL_TERMINAL.html",
    hullColor: "#064e3b",
    accentColor: "#eab308",
    marketIndex: "TATAR-X",
    marketIndexName: "Kazan Eurasian Commodity Index",
    primarySymbol: "TATN.ME",
    orbitalCoordinates: { lat: 55.8, lon: 49.1, altitudeKm: 420.8, speed: 0.0036 },
    telemetry: { reactorCore: "Volga Magnetic Pulse Cell 9.0 GW", shieldStatus: 99.0, warpDriveTier: "Warp 9.7", quantumEntropy: 0.0015 }
  },

  // ──────────────────────────────────────────────────────────
  // 18 LIBERAL SKY YACHTS (HIGH ENERGY, NIGHTLIFE, MODERN HEDONISM)
  // ──────────────────────────────────────────────────────────
  {
    id: "TR_LIB",
    name: "LİBERAL VİZYON (TULIP LOUNGE)",
    faction: "liberal",
    shipType: "yacht",
    alliance: "NATO",
    allianceName: "🔵 NATO MÜTTEFİKİ // LİBERAL TR",
    civilization: "Turkish Liberal",
    civilizationKey: "turkish",
    architecture: "Boğaz Cam Köşkü & Rakı-Lounge Terası",
    anchors: ["Cem Demirkan", "Melis Karahan"],
    theme: "Boğaz Günbatımı Rakı-Balık & Bebek Çatı Partisi",
    targetRegion: "İstanbul Boğazı / Bebek",
    primaryMission: "Sınırsız Eğlence, Lüks Tüketim & Finansal Akış",
    terminalUrl: "/LIBERAL_VIZYON_TURKISH_TERMINAL.html",
    hullColor: "#1e1b4b",
    accentColor: "#ec4899",
    marketIndex: "BIST TECH",
    marketIndexName: "BIST Teknoloji Endeksi",
    primarySymbol: "LOGO.IS",
    orbitalCoordinates: { lat: 41.0, lon: 29.0, altitudeKm: 425.0, speed: 0.0042 },
    telemetry: { reactorCore: "Bosporus Photonics Drive 7.8 GW", shieldStatus: 95.0, warpDriveTier: "Warp 9.2", quantumEntropy: 0.0045 }
  },
  {
    id: "UK_LIB",
    name: "PAX HORIZON (MIAMI SKY YACHT)",
    faction: "liberal",
    shipType: "yacht",
    alliance: "NATO",
    allianceName: "🔵 NATO MÜTTEFİKİ // LİBERAL US/UK",
    civilization: "Anglo Liberal",
    civilizationKey: "anglo",
    architecture: "Ultra Lüks Cam Katamaran & VIP Şampanya Lounge",
    anchors: ["Julian Vance", "Chloe Montgomery"],
    theme: "Miami & Ibiza Köpük Partisi & VIP Gece Hayatı",
    targetRegion: "Miami / Biscayne Bay",
    primaryMission: "Global Capital, Jet-Set & Yüksek Getirili Likidite",
    terminalUrl: "/PAX_HORIZON_LIBERAL_ENGLISH_TERMINAL.html",
    hullColor: "#0f172a",
    accentColor: "#f43f5e",
    marketIndex: "NASDAQ 100",
    marketIndexName: "Nasdaq Tech Top 100",
    primarySymbol: "NVDA",
    orbitalCoordinates: { lat: 25.7, lon: -80.2, altitudeKm: 428.0, speed: 0.0044 },
    telemetry: { reactorCore: "Miami Neon Supercharger 8.2 GW", shieldStatus: 96.2, warpDriveTier: "Warp 9.4", quantumEntropy: 0.0039 }
  },
  {
    id: "DE_LIB",
    name: "BERLIN BERGHAIN TECHNO CLUB",
    faction: "liberal",
    shipType: "neon_cube",
    alliance: "NATO",
    allianceName: "🔵 NATO // LİBERAL ALMANYA",
    civilization: "German Liberal",
    civilizationKey: "german",
    architecture: "Endüstriyel Beton & Lazer Kafes Dans Pisti",
    anchors: ["Felix Richter", "Hannah Vogel"],
    theme: "Kreuzberg 72-Saat Kesintisiz Elektronik Dans & Fintech",
    targetRegion: "Berlin / Spree",
    primaryMission: "Avrupa Gençlik Hareketi & Girişim Sermayesi",
    terminalUrl: "/BERLIN_TECHNO_GERMAN_TERMINAL.html",
    hullColor: "#09090b",
    accentColor: "#22c55e",
    marketIndex: "TecDAX",
    marketIndexName: "Frankfurt TecDAX Technology",
    primarySymbol: "IFX.DE",
    orbitalCoordinates: { lat: 52.5, lon: 13.4, altitudeKm: 426.4, speed: 0.0043 },
    telemetry: { reactorCore: "Spree Electro-Resonance Core 8.0 GW", shieldStatus: 95.8, warpDriveTier: "Warp 9.3", quantumEntropy: 0.0041 }
  },
  {
    id: "CN_LIB",
    name: "HARMONY SHANGHAI NEON",
    faction: "liberal",
    shipType: "neon_cube",
    alliance: "SCO_BRICS",
    allianceName: "🔴 SCO / BRICS+ LİBERAL KANAT",
    civilization: "Chinese Liberal",
    civilizationKey: "chinese",
    architecture: "Cyberpunk Cam Pagoda & Lazer Terası",
    anchors: ["Leo Zhang", "Vivian Wu"],
    theme: "The Bund Çatı Kulübü & Cyberpunk Neon Gece Hayatı",
    targetRegion: "Şanghay / Pudong",
    primaryMission: "Mega Şehir Partisi & Sınır Ötesi E-Ticaret",
    terminalUrl: "/HARMONY_GLOBAL_CHINESE_TERMINAL.html",
    hullColor: "#18181b",
    accentColor: "#a855f7",
    marketIndex: "ChiNext",
    marketIndexName: "Shenzhen ChiNext Growth Index",
    primarySymbol: "300750.SZ",
    orbitalCoordinates: { lat: 31.2, lon: 121.4, altitudeKm: 424.0, speed: 0.0043 },
    telemetry: { reactorCore: "Pudong Neon Plasma Ring 8.4 GW", shieldStatus: 96.5, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0035 }
  },
  {
    id: "JP_LIB",
    name: "NEO TOKYO SHIBUYA PULSE",
    faction: "liberal",
    shipType: "neon_cube",
    alliance: "QUAD_PACIFIC",
    allianceName: "🟠 QUAD PASİFİK LİBERAL KANAT",
    civilization: "Japanese Liberal",
    civilizationKey: "japanese",
    architecture: "Holografik Neon Cam & J-Pop Sahnesi",
    anchors: ["Ren Kurogane", "Sayaka Hoshino"],
    theme: "Roppongi Lüks Lounge & Elektronik Dans",
    targetRegion: "Tokyo / Shibuya",
    primaryMission: "24 Saat Kesintisiz Müzik & Dijital Sanat",
    terminalUrl: "/NEO_TOKYO_LIBERAL_JAPANESE_TERMINAL.html",
    hullColor: "#09090b",
    accentColor: "#06b6d4",
    marketIndex: "MOTHERS",
    marketIndexName: "Tokyo Growth & Startups",
    primarySymbol: "4385.T",
    orbitalCoordinates: { lat: 35.6, lon: 139.7, altitudeKm: 429.0, speed: 0.0045 },
    telemetry: { reactorCore: "Shibuya Hologram Fusion Core 8.5 GW", shieldStatus: 96.8, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0032 }
  },
  {
    id: "FR_LIB",
    name: "LUMIÈRE FRENCH RIVIERA",
    faction: "liberal",
    shipType: "yacht",
    alliance: "NATO",
    allianceName: "🔵 NATO / AB LİBERAL KANAT",
    civilization: "French Liberal",
    civilizationKey: "french",
    architecture: "Cannes Mega Yat & Şampanya Havuzu",
    anchors: ["Julien Moreau", "Léa Seydoux"],
    theme: "Saint-Tropez Kırmızı Halı & Şarap-Kokteyl Kulübü",
    targetRegion: "Cannes / Monaco",
    primaryMission: "Riviera Moda & Küresel Eğlence Yayını",
    terminalUrl: "/LUMIERE_LIBERAL_FRENCH_TERMINAL.html",
    hullColor: "#030712",
    accentColor: "#8b5cf6",
    marketIndex: "CAC MID 60",
    marketIndexName: "Paris Luxury & Mid-Cap",
    primarySymbol: "RMS.PA",
    orbitalCoordinates: { lat: 43.5, lon: 7.0, altitudeKm: 426.0, speed: 0.0041 },
    telemetry: { reactorCore: "Riviera Solar Yacht Turbine 7.9 GW", shieldStatus: 95.5, warpDriveTier: "Warp 9.2", quantumEntropy: 0.0042 }
  },
  {
    id: "AR_LIB",
    name: "DUBAI SKYLINE GOLD LOUNGE",
    faction: "liberal",
    shipType: "yacht",
    alliance: "GCC_ARAB",
    allianceName: "🟢 GCC LİBERAL KÖRFEZ KANADI",
    civilization: "Arab Liberal",
    civilizationKey: "arab",
    architecture: "Cam Burj Kulesi & Helikopter Pisti",
    anchors: ["Zayd Al-Maktoum", "Layla Mansur"],
    theme: "Palm Jumeirah Mega Yacht & Çöl Vaha Partisi",
    targetRegion: "Dubai / Marina",
    primaryMission: "Ultra Lüks Finans & Küresel Gayrimenkul Zirvesi",
    terminalUrl: "/DUBAI_SKYLINE_LIBERAL_ARABIC_TERMINAL.html",
    hullColor: "#022c22",
    accentColor: "#10b981",
    marketIndex: "DFM General",
    marketIndexName: "Dubai Financial Market",
    primarySymbol: "EMAAR.AE",
    orbitalCoordinates: { lat: 25.2, lon: 55.2, altitudeKm: 423.0, speed: 0.0046 },
    telemetry: { reactorCore: "Burj Quantum Helix 8.8 GW", shieldStatus: 97.4, warpDriveTier: "Warp 9.6", quantumEntropy: 0.0028 }
  },
  {
    id: "IR_LIB",
    name: "TEHRAN SYNTH SKYLINE",
    faction: "liberal",
    shipType: "neon_cube",
    alliance: "SCO_BRICS",
    allianceName: "🔴 SCO / BRICS+ LİBERAL KANAT",
    civilization: "Persian Liberal",
    civilizationKey: "persian",
    architecture: "Elbruz Cam Köşkü & Yeraltı Elektronik Müzik Sahnesi",
    anchors: ["Arash Kasravi", "Tara Bakhtiari"],
    theme: "Tahran Gençlik Yeraltı Kültürü & Fütürist Şiir",
    targetRegion: "Tahran / Şiraz",
    primaryMission: "Avrasya Yaratıcı Ekonomi & Gençlik Ağı",
    terminalUrl: "/TEHRAN_SYNTH_LIBERAL_PERSIAN_TERMINAL.html",
    hullColor: "#1c1917",
    accentColor: "#f59e0b",
    marketIndex: "IRAN-TECH",
    marketIndexName: "Tehran High-Tech Startups",
    primarySymbol: "IRO1MKBT0001",
    orbitalCoordinates: { lat: 35.7, lon: 51.4, altitudeKm: 425.5, speed: 0.0043 },
    telemetry: { reactorCore: "Damavand Resonance Cell 7.9 GW", shieldStatus: 95.2, warpDriveTier: "Warp 9.3", quantumEntropy: 0.0040 }
  },
  {
    id: "RU_LIB",
    name: "NEVA NIGHTS SOCHI RIVIERA",
    faction: "liberal",
    shipType: "yacht",
    alliance: "SCO_BRICS",
    allianceName: "🔴 SCO / BRICS+ LİBERAL KANAT",
    civilization: "Russian Liberal",
    civilizationKey: "russian",
    architecture: "Karadeniz Kristal Yat & Votka Lounge",
    anchors: ["Nikolai Romanov", "Polina Petrova"],
    theme: "St. Petersburg Beyaz Geceler & Lüks Kokteyl Kulübü",
    targetRegion: "Soçi / Yalta",
    primaryMission: "Yaz Kulübü Yayını & Lüks Tüketim",
    terminalUrl: "/NEVA_NIGHTS_LIBERAL_RUSSIAN_TERMINAL.html",
    hullColor: "#0f172a",
    accentColor: "#38bdf8",
    marketIndex: "RTS Index",
    marketIndexName: "Moscow Dollar-denominated RTS",
    primarySymbol: "YNDX.ME",
    orbitalCoordinates: { lat: 43.6, lon: 39.7, altitudeKm: 424.0, speed: 0.0042 },
    telemetry: { reactorCore: "Neva Aurora Dynamo 8.1 GW", shieldStatus: 96.0, warpDriveTier: "Warp 9.4", quantumEntropy: 0.0037 }
  },
  {
    id: "IN_LIB",
    name: "BOLLYWOOD PULSE GOA",
    faction: "liberal",
    shipType: "vimana",
    alliance: "SCO_BRICS",
    allianceName: "🔴 BRICS+ LİBERAL KANAT",
    civilization: "Indian Liberal",
    civilizationKey: "indian",
    architecture: "Neon Lotus & Plaj Dans Güvertesi",
    anchors: ["Kabir Kapoor", "Ananya Sen"],
    theme: "Mumbai Çatı Dans Festivali & Goa Plaj Eğlencesi",
    targetRegion: "Goa / Mumbai",
    primaryMission: "Sinema, Festival & Gençlik Sermayesi",
    terminalUrl: "/BOLLYWOOD_PULSE_LIBERAL_HINDI_TERMINAL.html",
    hullColor: "#451a03",
    accentColor: "#f59e0b",
    marketIndex: "BSE SENSEX TECH",
    marketIndexName: "Bombay Stock Exchange Digital",
    primarySymbol: "INFY.BO",
    orbitalCoordinates: { lat: 15.4, lon: 73.8, altitudeKm: 425.0, speed: 0.0043 },
    telemetry: { reactorCore: "Goa Solaris Wave Engine 8.3 GW", shieldStatus: 96.4, warpDriveTier: "Warp 9.4", quantumEntropy: 0.0034 }
  },
  {
    id: "ES_LIB",
    name: "IBIZA FIESTA BALEARIC",
    faction: "liberal",
    shipType: "yacht",
    alliance: "NATO",
    allianceName: "🔵 NATO MÜTTEFİKİ // LİBERAL İSPANYA",
    civilization: "Spanish Liberal",
    civilizationKey: "spanish",
    architecture: "Açık Hava Dans Pisti & Lazer Fıskiyesi",
    anchors: ["Carlos Mendoza", "Isabella Gomez"],
    theme: "Balearik Adaları Mega Dans Güvertesi & Gece Kulübü",
    targetRegion: "Ibiza / Formentera",
    primaryMission: "Elektronik Müzik Devriyesi & Festival",
    terminalUrl: "/IBIZA_FIESTA_LIBERAL_SPANISH_TERMINAL.html",
    hullColor: "#18181b",
    accentColor: "#f43f5e",
    marketIndex: "IBEX MEDIUM",
    marketIndexName: "Madrid Lifestyle & Tourism",
    primarySymbol: "ITX.MC",
    orbitalCoordinates: { lat: 38.9, lon: 1.4, altitudeKm: 427.0, speed: 0.0047 },
    telemetry: { reactorCore: "Balearic Foam-Laser Pulse 8.6 GW", shieldStatus: 97.0, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0031 }
  },
  {
    id: "IT_LIB",
    name: "MILAN FASHION SKY YACHT",
    faction: "liberal",
    shipType: "yacht",
    alliance: "NATO",
    allianceName: "🔵 NATO // LİBERAL İTALYA",
    civilization: "Italian Liberal",
    civilizationKey: "roman",
    architecture: "Karbon-Fiber Katamaran & Podyum Işıkları",
    anchors: ["Lorenzo Moretti", "Chiara Rossi"],
    theme: "Milano Moda Haftası, Como Gölü Yat Partisi & Lüks Tasarım",
    targetRegion: "Milano / Como Gölü",
    primaryMission: "Küresel Moda & Lüks Finans Yayını",
    terminalUrl: "/MILAN_FASHION_LIBERAL_ITALIAN_TERMINAL.html",
    hullColor: "#0f172a",
    accentColor: "#d946ef",
    marketIndex: "MIB ESG",
    marketIndexName: "Milano Luxury & Design Index",
    primarySymbol: "MONC.MI",
    orbitalCoordinates: { lat: 45.4, lon: 9.2, altitudeKm: 426.8, speed: 0.0044 },
    telemetry: { reactorCore: "Lombard Carbon Supercharger 8.0 GW", shieldStatus: 95.9, warpDriveTier: "Warp 9.3", quantumEntropy: 0.0038 }
  },
  {
    id: "SE_LIB",
    name: "STOCKHOLM AURORA LOUNGE",
    faction: "liberal",
    shipType: "yacht",
    alliance: "NATO",
    allianceName: "🔵 NATO // LİBERAL NORDİK",
    civilization: "Nordic Liberal",
    civilizationKey: "nordic",
    architecture: "İskandinav Ahşap-Cam Tasarımı & Kuzey Işıkları Terası",
    anchors: ["Elias Bergström", "Freja Nilsson"],
    theme: "Stockholm Fintech Unicorns & Fiyort Gece Kulübü",
    targetRegion: "Stockholm / Gotland",
    primaryMission: "Yeşil Enerji, Unicorn Finans & İskandinav Tasarım",
    terminalUrl: "/STOCKHOLM_AURORA_LIBERAL_NORDIC_TERMINAL.html",
    hullColor: "#042f2e",
    accentColor: "#14b8a6",
    marketIndex: "FIRST NORTH",
    marketIndexName: "Nordic Tech Startups",
    primarySymbol: "SPOT",
    orbitalCoordinates: { lat: 59.3, lon: 18.1, altitudeKm: 427.5, speed: 0.0042 },
    telemetry: { reactorCore: "Aurora Hydro-Quantum Cell 8.2 GW", shieldStatus: 96.3, warpDriveTier: "Warp 9.4", quantumEntropy: 0.0036 }
  },
  {
    id: "AF_LIB",
    name: "AFRO BEATS LAGOS SUNSET",
    faction: "liberal",
    shipType: "bamboo",
    alliance: "AU_AFRICA",
    allianceName: "🟡 AFRİKA BİRLİĞİ LİBERAL KANAT",
    civilization: "Pan-African Liberal",
    civilizationKey: "african",
    architecture: "Fütürist Bambu & Altın Teras",
    anchors: ["Femi Adeleke", "Nandi Zulu"],
    theme: "Victoria Island VIP Kulübü & Afro-Dans",
    targetRegion: "Lagos / Cape Town",
    primaryMission: "Afro-Fütürist Festival & Yaratıcı Ekonomi",
    terminalUrl: "/AFRO_BEATS_LIBERAL_AFRICAN_TERMINAL.html",
    hullColor: "#1c1917",
    accentColor: "#eab308",
    marketIndex: "NGX 30",
    marketIndexName: "Nigerian Exchange All-Share",
    primarySymbol: "MTNN.LG",
    orbitalCoordinates: { lat: 6.5, lon: 3.3, altitudeKm: 426.0, speed: 0.0044 },
    telemetry: { reactorCore: "Victoria Solar Bamboo Drive 8.1 GW", shieldStatus: 96.0, warpDriveTier: "Warp 9.3", quantumEntropy: 0.0039 }
  },
  {
    id: "LA_LIB",
    name: "RIO SAMBA SKY CARNIVAL",
    faction: "liberal",
    shipType: "yacht",
    alliance: "LATAM_MERCOSUR",
    allianceName: "🟣 MERCOSUR LİBERAL KANAT",
    civilization: "Latin American Liberal",
    civilizationKey: "latin",
    architecture: "Copacabana Cam Dalga & Karnaval Lazer Tribünü",
    anchors: ["Mateo Silva", "Gabriela Santos"],
    theme: "Rio Karnavalı, Samba Ruhu & Tropikal Kokteyl Partisi",
    targetRegion: "Rio de Janeiro / Sao Paulo",
    primaryMission: "Latin Amerika Yaratıcı Enerji & Müzik Yayını",
    terminalUrl: "/RIO_SAMBA_LIBERAL_LATIN_TERMINAL.html",
    hullColor: "#1e1b4b",
    accentColor: "#38bdf8",
    marketIndex: "B3 SMALL",
    marketIndexName: "Brazil Growth & Creative Economy",
    primarySymbol: "NU",
    orbitalCoordinates: { lat: -22.9, lon: -43.2, altitudeKm: 427.8, speed: 0.0045 },
    telemetry: { reactorCore: "Copacabana Wave Generator 8.4 GW", shieldStatus: 96.7, warpDriveTier: "Warp 9.5", quantumEntropy: 0.0033 }
  },
  {
    id: "KR_LIB",
    name: "SEOUL CYBER K-POP CITADEL",
    faction: "liberal",
    shipType: "neon_cube",
    alliance: "QUAD_PACIFIC",
    allianceName: "🟠 DOĞU ASYA LİBERAL KANAT",
    civilization: "Korean Liberal",
    civilizationKey: "korean",
    architecture: "Gangnam Hologram Kulesi & K-Pop Dans Arenası",
    anchors: ["Tae-hyun Jung", "Soo-jin Lee"],
    theme: "Gangnam Gece Kulüpleri, K-Pop Hologram Konserleri & Web3",
    targetRegion: "Seul / Gangnam",
    primaryMission: "Küresel Dijital Kültür & K-Fintech Yayını",
    terminalUrl: "/SEOUL_CYBER_LIBERAL_KOREAN_TERMINAL.html",
    hullColor: "#09090b",
    accentColor: "#f43f5e",
    marketIndex: "KOSDAQ",
    marketIndexName: "Korea Tech & Media Index",
    primarySymbol: "352820.KQ",
    orbitalCoordinates: { lat: 37.5, lon: 127.0, altitudeKm: 429.2, speed: 0.0046 },
    telemetry: { reactorCore: "Gangnam Quantum Synth Matrix 8.7 GW", shieldStatus: 97.2, warpDriveTier: "Warp 9.6", quantumEntropy: 0.0029 }
  },
  {
    id: "SEA_LIB",
    name: "BALI TROPICS FLOAT LOUNGE",
    faction: "liberal",
    shipType: "yacht",
    alliance: "ASEAN_PACIFIC",
    allianceName: "🟤 ASEAN LİBERAL KANAT",
    civilization: "Southeast Asian Liberal",
    civilizationKey: "southeast_asian",
    architecture: "Ubud Bambu-Cam Villa & Sonsuzluk Havuzu Terası",
    anchors: ["Aris Thorne", "Maya Lestari"],
    theme: "Seminyak Günbatımı Kulübü, Dijital Göçebeler & Kripto Vaha",
    targetRegion: "Bali / Singapur",
    primaryMission: "Dijital Göçebe Finans & Tropikal Yaşam Yayını",
    terminalUrl: "/BALI_TROPICS_LIBERAL_SEA_TERMINAL.html",
    hullColor: "#022c22",
    accentColor: "#10b981",
    marketIndex: "SGX Tech",
    marketIndexName: "Singapore Digital & Innovation",
    primarySymbol: "GRAB",
    orbitalCoordinates: { lat: -8.4, lon: 115.2, altitudeKm: 426.5, speed: 0.0044 },
    telemetry: { reactorCore: "Tropical Biomimetic Cell 8.0 GW", shieldStatus: 95.7, warpDriveTier: "Warp 9.3", quantumEntropy: 0.0040 }
  },
  {
    id: "TT_LIB",
    name: "KAZAN SILK OASIS LOUNGE",
    faction: "liberal",
    shipType: "yacht",
    alliance: "SCO_BRICS",
    allianceName: "🔴 AVRASYA LİBERAL KANAT",
    civilization: "Tatar / Eurasian Liberal",
    civilizationKey: "tatar",
    architecture: "İdil Kristal Kemerleri & İpek Yolu Lounge Terası",
    anchors: ["Timur Sabirov", "Alsou Galiullina"],
    theme: "Kazan İnovasyon Vadisi, İpek Yolu Kahvehaneleri & Fintech",
    targetRegion: "Kazan / Samara",
    primaryMission: "Avrasya Teknoloji Köprüsü & Dijital İpek Yolu",
    terminalUrl: "/KAZAN_SILK_LIBERAL_TATAR_TERMINAL.html",
    hullColor: "#064e3b",
    accentColor: "#38bdf8",
    marketIndex: "IDIL-FIN",
    marketIndexName: "Volga Digital Commerce",
    primarySymbol: "OZON.ME",
    orbitalCoordinates: { lat: 55.8, lon: 49.2, altitudeKm: 426.0, speed: 0.0042 },
    telemetry: { reactorCore: "Silk Road Photonic Dynamo 8.2 GW", shieldStatus: 96.2, warpDriveTier: "Warp 9.4", quantumEntropy: 0.0037 }
  }
];

export const CIVILIZATIONS_LIST = [
  { key: "turkish", name: "Türk Dünyası & Selçuklu", region: "Ankara / İstanbul / Samsun", flag: "🇹🇷", defAlliance: "NATO" },
  { key: "anglo", name: "Anglo-Sakson & Kraliyet", region: "Londra / New York / Miami", flag: "🇬🇧", defAlliance: "NATO" },
  { key: "german", name: "Alman & Prusya / Hanseatic", region: "Berlin / Frankfurt", flag: "🇩🇪", defAlliance: "NATO" },
  { key: "chinese", name: "Çin & Han / Tang Hanedanı", region: "Pekin / Şanghay", flag: "🇨🇳", defAlliance: "SCO_BRICS" },
  { key: "japanese", name: "Japon & Tokugawa / Samuray", region: "Tokyo / Kyoto", flag: "🇯🇵", defAlliance: "QUAD_PACIFIC" },
  { key: "french", name: "Fransız & Bourbon / Versailles", region: "Paris / Riviera", flag: "🇫🇷", defAlliance: "NATO" },
  { key: "arab", name: "Arap & Abbasi / Körfez", region: "Riyad / Dubai", flag: "🇸🇦", defAlliance: "GCC_ARAB" },
  { key: "persian", name: "Pers & Ahameniş / Persepolis", region: "Tahran / İsfahan", flag: "🇮🇷", defAlliance: "SCO_BRICS" },
  { key: "russian", name: "Slav & Rurik / Moskova", region: "Moskova / St. Petersburg", flag: "🇷🇺", defAlliance: "SCO_BRICS" },
  { key: "indian", name: "Hint & Maurya / Vedik", region: "Yeni Delhi / Mumbai", flag: "🇮🇳", defAlliance: "SCO_BRICS" },
  { key: "spanish", name: "İspanyol & Habsburgo / İberya", region: "Madrid / Balearik", flag: "🇪🇸", defAlliance: "NATO" },
  { key: "roman", name: "Roma & Nova Roma / İtalya", region: "Roma / Milano", flag: "🇮🇹", defAlliance: "NATO" },
  { key: "nordic", name: "Nordik & Viking / İskandinav", region: "Stockholm / Oslo", flag: "🇸🇪", defAlliance: "NATO" },
  { key: "african", name: "Pan-Afrika & Kilwa / Zimbabve", region: "Addis Ababa / Lagos", flag: "🌍", defAlliance: "AU_AFRICA" },
  { key: "latin", name: "Latin Amerika & Aztek / Copacabana", region: "Mexico City / Rio", flag: "🇧🇷", defAlliance: "LATAM_MERCOSUR" },
  { key: "korean", name: "Kore & Joseon / Gangnam", region: "Seul / Busan", flag: "🇰🇷", defAlliance: "QUAD_PACIFIC" },
  { key: "southeast_asian", name: "Güneydoğu Asya & Ayutthaya / Bali", region: "Bangkok / Bali", flag: "🇹🇭", defAlliance: "ASEAN_PACIFIC" },
  { key: "tatar", name: "Tatar & İdil-Ural / Altın Orda", region: "Kazan / İdil", flag: "🏹", defAlliance: "SCO_BRICS" }
];

export const allFleet = CIVILIZATIONAL_FLEET;

export function getFleetStats() {
  const totalShips = CIVILIZATIONAL_FLEET.length;
  const liberalShips = CIVILIZATIONAL_FLEET.filter((s) => s.faction === "liberal").length;
  const conservativeShips = CIVILIZATIONAL_FLEET.filter((s) => s.faction === "conservative").length;
  const natoShips = CIVILIZATIONAL_FLEET.filter((s) => s.alliance === "NATO").length;
  const scoBricsShips = CIVILIZATIONAL_FLEET.filter((s) => s.alliance === "SCO_BRICS").length;
  const quadShips = CIVILIZATIONAL_FLEET.filter((s) => s.alliance === "QUAD_PACIFIC").length;
  const civilizationsCount = CIVILIZATIONS_LIST.length;

  return {
    totalShips,
    liberalShips,
    conservativeShips,
    civilizations: civilizationsCount,
    alliances: {
      nato: natoShips,
      scoBrics: scoBricsShips,
      quad: quadShips,
      gcc: CIVILIZATIONAL_FLEET.filter((s) => s.alliance === "GCC_ARAB").length,
      au: CIVILIZATIONAL_FLEET.filter((s) => s.alliance === "AU_AFRICA").length,
      latam: CIVILIZATIONAL_FLEET.filter((s) => s.alliance === "LATAM_MERCOSUR").length,
      asean: CIVILIZATIONAL_FLEET.filter((s) => s.alliance === "ASEAN_PACIFIC").length,
    },
  };
}

