export interface GlobalBourse {
  id: string;
  name: string;
  shortCode: string;
  city: string;
  country: string;
  flag: string;
  lat: number;
  lng: number;
  primaryIndex: string;
  indexValue: number;
  change24h: number;
  marketCapTrillionUSD: number;
  currency: string;
  currencySymbol: string;
  fxRateVsUSD: number;
  centralBank: string;
  policyRatePercent: number;
  yield10YPercent: number;
  status: 'OPEN' | 'CLOSED' | 'PRE_MARKET' | 'POST_MARKET';
  geopoliticalRiskSensitivity: 'HIGH' | 'EXTREME' | 'MODERATE' | 'LOW';
  keySectors: string[];
  safeHavenFlowTarget: boolean;
  capitalFlightPressure: 'NORMAL' | 'ELEVATED' | 'SEVERE';
}

export interface GeofinancialCommodityShock {
  commodity: string;
  symbol: string;
  currentPrice: number;
  unit: string;
  change24h: number;
  conflictSensitivity: 'HIGH' | 'CRITICAL' | 'EXTREME';
  chokepointRisk: string;
}

export const GLOBAL_BOURSES: GlobalBourse[] = [
  {
    id: 'nyse-nasdaq',
    name: 'New York Stock Exchange & NASDAQ',
    shortCode: 'NYSE / NSDQ',
    city: 'New York',
    country: 'United States',
    flag: '🇺🇸',
    lat: 40.7069,
    lng: -74.0089,
    primaryIndex: 'S&P 500 / NASDAQ 100',
    indexValue: 5684.20,
    change24h: 0.65,
    marketCapTrillionUSD: 52.4,
    currency: 'USD',
    currencySymbol: '$',
    fxRateVsUSD: 1.0000,
    centralBank: 'Federal Reserve (Fed)',
    policyRatePercent: 4.75,
    yield10YPercent: 4.08,
    status: 'OPEN',
    geopoliticalRiskSensitivity: 'HIGH',
    keySectors: ['Mega-Cap Tech', 'Semiconductors', 'Defense & Aerospace', 'Banking'],
    safeHavenFlowTarget: true,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'lse-london',
    name: 'London Stock Exchange',
    shortCode: 'LSE',
    city: 'London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    lat: 51.5152,
    lng: -0.0998,
    primaryIndex: 'FTSE 100',
    indexValue: 8275.50,
    change24h: -0.22,
    marketCapTrillionUSD: 3.8,
    currency: 'GBP',
    currencySymbol: '£',
    fxRateVsUSD: 1.3120,
    centralBank: 'Bank of England (BoE)',
    policyRatePercent: 5.00,
    yield10YPercent: 3.92,
    status: 'CLOSED',
    geopoliticalRiskSensitivity: 'HIGH',
    keySectors: ['Energy (BP/Shell)', 'Mining & Metals', 'Global Banking', 'Insurance'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'fra-frankfurt',
    name: 'Deutsche Börse (Frankfurt)',
    shortCode: 'FWB / DAX',
    city: 'Frankfurt',
    country: 'Germany',
    flag: '🇩🇪',
    lat: 50.1153,
    lng: 8.6781,
    primaryIndex: 'DAX 40',
    indexValue: 18690.10,
    change24h: 0.38,
    marketCapTrillionUSD: 2.3,
    currency: 'EUR',
    currencySymbol: '€',
    fxRateVsUSD: 1.1080,
    centralBank: 'European Central Bank (ECB)',
    policyRatePercent: 3.65,
    yield10YPercent: 2.15,
    status: 'CLOSED',
    geopoliticalRiskSensitivity: 'EXTREME',
    keySectors: ['Industrial Engineering', 'Automotive', 'Chemicals', 'Green Energy'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'ELEVATED',
  },
  {
    id: 'tse-tokyo',
    name: 'Tokyo Stock Exchange',
    shortCode: 'TSE',
    city: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    lat: 35.6828,
    lng: 139.7772,
    primaryIndex: 'Nikkei 225',
    indexValue: 36581.70,
    change24h: -0.85,
    marketCapTrillionUSD: 6.5,
    currency: 'JPY',
    currencySymbol: '¥',
    fxRateVsUSD: 142.30,
    centralBank: 'Bank of Japan (BOJ)',
    policyRatePercent: 0.25,
    yield10YPercent: 0.86,
    status: 'OPEN',
    geopoliticalRiskSensitivity: 'HIGH',
    keySectors: ['Robotics', 'Automotive', 'Precision Electronics', 'Semiconductor Equipment'],
    safeHavenFlowTarget: true,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'sse-shanghai',
    name: 'Shanghai & Shenzhen Stock Exchange',
    shortCode: 'SSE / SZSE',
    city: 'Shanghai',
    country: 'China',
    flag: '🇨🇳',
    lat: 31.2304,
    lng: 121.4737,
    primaryIndex: 'CSI 300 / SSE Composite',
    indexValue: 3210.40,
    change24h: 1.45,
    marketCapTrillionUSD: 10.9,
    currency: 'CNY',
    currencySymbol: '¥',
    fxRateVsUSD: 7.0950,
    centralBank: 'People\'s Bank of China (PBOC)',
    policyRatePercent: 3.35,
    yield10YPercent: 2.12,
    status: 'OPEN',
    geopoliticalRiskSensitivity: 'EXTREME',
    keySectors: ['State-Owned Enterprises', 'Electric Vehicles', 'Solar Tech', 'Semiconductors'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'ELEVATED',
  },
  {
    id: 'hkex-hongkong',
    name: 'Hong Kong Exchanges and Clearing',
    shortCode: 'HKEX',
    city: 'Hong Kong',
    country: 'Hong Kong SAR',
    flag: '🇭🇰',
    lat: 22.2833,
    lng: 114.1588,
    primaryIndex: 'Hang Seng Index',
    indexValue: 17422.30,
    change24h: 0.95,
    marketCapTrillionUSD: 4.2,
    currency: 'HKD',
    currencySymbol: 'HK$',
    fxRateVsUSD: 7.7950,
    centralBank: 'Hong Kong Monetary Authority (HKMA)',
    policyRatePercent: 5.00,
    yield10YPercent: 3.48,
    status: 'OPEN',
    geopoliticalRiskSensitivity: 'HIGH',
    keySectors: ['Cross-Border Finance', 'E-Commerce Tech', 'Real Estate', 'Logistics'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'bist-istanbul',
    name: 'Borsa Istanbul',
    shortCode: 'BIST',
    city: 'Istanbul',
    country: 'Turkiye',
    flag: '🇹🇷',
    lat: 41.1114,
    lng: 29.0558,
    primaryIndex: 'BIST 100',
    indexValue: 9850.25,
    change24h: 1.15,
    marketCapTrillionUSD: 0.38,
    currency: 'TRY',
    currencySymbol: '₺',
    fxRateVsUSD: 34.05,
    centralBank: 'Central Bank of Republic of Turkiye (CBRT)',
    policyRatePercent: 50.00,
    yield10YPercent: 28.40,
    status: 'CLOSED',
    geopoliticalRiskSensitivity: 'EXTREME',
    keySectors: ['Defense (Aselsan)', 'Banking', 'Aviation (Turkish Airlines)', 'Steel & Energy'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'ELEVATED',
  },
  {
    id: 'tadawul-riyadh',
    name: 'Saudi Exchange (Tadawul)',
    shortCode: 'TADAWUL',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    lat: 24.7136,
    lng: 46.6753,
    primaryIndex: 'TASI Index',
    indexValue: 11840.60,
    change24h: -0.15,
    marketCapTrillionUSD: 2.8,
    currency: 'SAR',
    currencySymbol: '﷼',
    fxRateVsUSD: 3.7510,
    centralBank: 'Saudi Central Bank (SAMA)',
    policyRatePercent: 5.50,
    yield10YPercent: 4.60,
    status: 'OPEN',
    geopoliticalRiskSensitivity: 'EXTREME',
    keySectors: ['Aramco Oil & Gas', 'Petrochemicals (SABIC)', 'Sovereign Wealth (PIF)', 'Islamic Banking'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'six-zurich',
    name: 'SIX Swiss Exchange',
    shortCode: 'SIX',
    city: 'Zurich',
    country: 'Switzerland',
    flag: '🇨🇭',
    lat: 47.3769,
    lng: 8.5417,
    primaryIndex: 'SMI (Swiss Market Index)',
    indexValue: 12040.10,
    change24h: 0.12,
    marketCapTrillionUSD: 2.1,
    currency: 'CHF',
    currencySymbol: 'CHF',
    fxRateVsUSD: 0.8490,
    centralBank: 'Swiss National Bank (SNB)',
    policyRatePercent: 1.25,
    yield10YPercent: 0.45,
    status: 'CLOSED',
    geopoliticalRiskSensitivity: 'LOW',
    keySectors: ['Private Banking', 'Pharmaceuticals (Novartis/Roche)', 'Precision Watches', 'Commodity Trading'],
    safeHavenFlowTarget: true,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'sgx-singapore',
    name: 'Singapore Exchange',
    shortCode: 'SGX',
    city: 'Singapore',
    country: 'Singapore',
    flag: '🇸🇬',
    lat: 1.2833,
    lng: 103.8500,
    primaryIndex: 'Straits Times Index (STI)',
    indexValue: 3515.80,
    change24h: 0.40,
    marketCapTrillionUSD: 0.85,
    currency: 'SGD',
    currencySymbol: 'S$',
    fxRateVsUSD: 1.3010,
    centralBank: 'Monetary Authority of Singapore (MAS)',
    policyRatePercent: 3.75,
    yield10YPercent: 2.75,
    status: 'OPEN',
    geopoliticalRiskSensitivity: 'LOW',
    keySectors: ['Wealth Management', 'Maritime Logistics & Bunkering', 'Semiconductors', 'REITs'],
    safeHavenFlowTarget: true,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'nse-mumbai',
    name: 'National Stock Exchange of India',
    shortCode: 'NSE / BSE',
    city: 'Mumbai',
    country: 'India',
    flag: '🇮🇳',
    lat: 19.0760,
    lng: 72.8777,
    primaryIndex: 'NIFTY 50 / SENSEX',
    indexValue: 25356.50,
    change24h: 0.78,
    marketCapTrillionUSD: 5.3,
    currency: 'INR',
    currencySymbol: '₹',
    fxRateVsUSD: 83.95,
    centralBank: 'Reserve Bank of India (RBI)',
    policyRatePercent: 6.50,
    yield10YPercent: 6.85,
    status: 'OPEN',
    geopoliticalRiskSensitivity: 'MODERATE',
    keySectors: ['IT Services (TCS/Infosys)', 'Conglomerates (Reliance/Tata)', 'Pharma', 'Banking'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'NORMAL',
  },
  {
    id: 'asx-sydney',
    name: 'Australian Securities Exchange',
    shortCode: 'ASX',
    city: 'Sydney',
    country: 'Australia',
    flag: '🇦🇺',
    lat: -33.8688,
    lng: 151.2093,
    primaryIndex: 'S&P/ASX 200',
    indexValue: 8120.40,
    change24h: 0.32,
    marketCapTrillionUSD: 1.9,
    currency: 'AUD',
    currencySymbol: 'A$',
    fxRateVsUSD: 0.6720,
    centralBank: 'Reserve Bank of Australia (RBA)',
    policyRatePercent: 4.35,
    yield10YPercent: 3.98,
    status: 'CLOSED',
    geopoliticalRiskSensitivity: 'MODERATE',
    keySectors: ['Critical Minerals (Lithium/Uranium)', 'Iron Ore (BHP/Rio Tinto)', 'LNG Exports', 'Banking'],
    safeHavenFlowTarget: false,
    capitalFlightPressure: 'NORMAL',
  },
];

export const GEOFINANCIAL_COMMODITY_SHOCKS: GeofinancialCommodityShock[] = [
  {
    commodity: 'Gold Bullion (Safe-Haven Reserve)',
    symbol: 'XAU/USD',
    currentPrice: 2580.40,
    unit: 'USD/oz',
    change24h: 1.25,
    conflictSensitivity: 'EXTREME',
    chokepointRisk: 'Global Central Bank Inflows / Geopolitical De-Dollarization',
  },
  {
    commodity: 'Brent Crude Oil',
    symbol: 'BRENT',
    currentPrice: 72.85,
    unit: 'USD/bbl',
    change24h: 2.10,
    conflictSensitivity: 'CRITICAL',
    chokepointRisk: 'Strait of Hormuz & Bab el-Mandeb Tanker Transit Interdiction',
  },
  {
    commodity: 'European Natural Gas (Dutch TTF)',
    symbol: 'TTF_GAS',
    currentPrice: 36.40,
    unit: 'EUR/MWh',
    change24h: 3.45,
    conflictSensitivity: 'CRITICAL',
    chokepointRisk: 'Russian Transit Pipeline Invalidation & LNG Terminal Vulnerability',
  },
  {
    commodity: 'Agricultural Milling Wheat',
    symbol: 'WHEAT',
    currentPrice: 575.25,
    unit: 'USD/bushel',
    change24h: 0.85,
    conflictSensitivity: 'HIGH',
    chokepointRisk: 'Black Sea Grain Corridor & Odessa Port Missile Strikes',
  },
  {
    commodity: 'Physical Uranium (U3O8 Yellowcake)',
    symbol: 'URANIUM',
    currentPrice: 82.50,
    unit: 'USD/lb',
    change24h: 0.40,
    conflictSensitivity: 'CRITICAL',
    chokepointRisk: 'Kazakhstan & Niger Export Logistics / Nuclear Enrichment Security',
  },
  {
    commodity: 'Bitcoin (Digital Sovereign Reserve Asset)',
    symbol: 'BTC/USD',
    currentPrice: 58450.00,
    unit: 'USD',
    change24h: 2.80,
    conflictSensitivity: 'HIGH',
    chokepointRisk: 'Capital Flight from Sanctioned / War-Torn Fiat Currencies',
  },
];
