/**
 * NUR EARTH — 136 Active Military Combat Units & Order of Battle (NATO ORBAT)
 * Complete military disposition, frontline coordinates, combat readiness, commanders, and casualty data.
 */

export interface TacticalMilitaryUnit {
  id: string;
  name: string;
  designation: string;
  faction: "UKRAINE" | "RUSSIA" | "ISRAEL" | "HEZBOLLAH" | "US_COALITION" | "HOUTHI" | "TAIWAN" | "CHINA" | "SUDAN_SAF" | "SUDAN_RSF" | "SAHEL_ALLIANCE" | "REGIONAL";
  theater: "EASTERN_EUROPE" | "MIDDLE_EAST" | "RED_SEA" | "INDO_PACIFIC" | "AFRICA" | "CENTRAL_ASIA";
  unitType: "ARMOR" | "MECHANIZED" | "INFANTRY" | "AIRBORNE" | "ARTILLERY_MISSILE" | "AIR_DEFENSE" | "NAVAL_TASK_FORCE" | "DRONE_SWARM" | "SPECIAL_FORCES";
  icon: string;
  lat: number;
  lon: number;
  personnelStrength: number;
  combatReadinessPct: number;
  commander: string;
  equipment: string[];
  casualtyEstimate: number;
  status: "ACTIVE_ENGAGED" | "FORTIFIED" | "COUNTER_OFFENSIVE" | "ATTRITED" | "STRIKE_ALERT";
  frontlineSector: string;
  correlatedAssets: string[];
}

export interface FrontlineBoundary {
  id: string;
  name: string;
  theater: string;
  color: string;
  points: [number, number][]; // [lat, lon]
}

/* ─────────────────────────────────────────────────────────────────────────────
   136 ACTIVE COMBAT UNITS (FULL THEATER ORDER OF BATTLE)
   ───────────────────────────────────────────────────────────────────────────── */
export const ACTIVE_136_MILITARY_UNITS: TacticalMilitaryUnit[] = [
  // ── EASTERN EUROPE THEATER (UKRAINE - RUSSIA FRONTLINE & KURSK SALIENT) ──
  {
    id: "unit-001",
    name: "47th Separate Mechanized Brigade 'Magura'",
    designation: "47th OMBr (AFU)",
    faction: "UKRAINE",
    theater: "EASTERN_EUROPE",
    unitType: "MECHANIZED",
    icon: "🚜",
    lat: 48.28,
    lon: 37.18,
    personnelStrength: 4500,
    combatReadinessPct: 82,
    commander: "Col. Oleksandr Pavlii",
    equipment: ["M1A1 Abrams", "M2A2 Bradley IFV", "M109A6 Paladin"],
    casualtyEstimate: 1240,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Pokrovsk Defense Axis",
    correlatedAssets: ["WHEAT=F", "EUR/USD", "DEFENSE_ETF"],
  },
  {
    id: "unit-002",
    name: "3rd Separate Assault Brigade (Azov Command)",
    designation: "3rd OShBr (AFU)",
    faction: "UKRAINE",
    theater: "EASTERN_EUROPE",
    unitType: "SPECIAL_FORCES",
    icon: "⚔️",
    lat: 48.86,
    lon: 37.75,
    personnelStrength: 5200,
    combatReadinessPct: 88,
    commander: "Col. Andriy Biletsky",
    equipment: ["M113 APC", "MaxxPro MRAP", "FPV Strike Drone Swarms"],
    casualtyEstimate: 1650,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Toretsk–Chasiv Yar Flank",
    correlatedAssets: ["STEEL", "TITANIUM"],
  },
  {
    id: "unit-003",
    name: "82nd Air Assault Brigade",
    designation: "82nd ODShBr (AFU)",
    faction: "UKRAINE",
    theater: "EASTERN_EUROPE",
    unitType: "AIRBORNE",
    icon: "🦅",
    lat: 51.20,
    lon: 35.27,
    personnelStrength: 3800,
    combatReadinessPct: 90,
    commander: "Col. Pavlo Rozlach",
    equipment: ["Challenger 2", "Stryker ICV", "Marder 1A3"],
    casualtyEstimate: 780,
    status: "COUNTER_OFFENSIVE",
    frontlineSector: "Kursk Salient (Sudzha–Korenevo)",
    correlatedAssets: ["NG.US (Gas Transit)", "RUB=X"],
  },
  {
    id: "unit-004",
    name: "92nd Assault Brigade 'Ivan Sirko'",
    designation: "92nd OShBr (AFU)",
    faction: "UKRAINE",
    theater: "EASTERN_EUROPE",
    unitType: "INFANTRY",
    icon: "⚔️",
    lat: 50.15,
    lon: 36.65,
    personnelStrength: 4100,
    combatReadinessPct: 85,
    commander: "Col. Pavlo Fedosenko",
    equipment: ["BTR-4E Bucephalus", "T-64BV Mod 2017", "Archer Artillery"],
    casualtyEstimate: 920,
    status: "FORTIFIED",
    frontlineSector: "Kharkiv North–Vovchansk Axis",
    correlatedAssets: ["AGRI_INDEX"],
  },
  {
    id: "unit-005",
    name: "76th Guards Air Assault Division (Pskov VDV)",
    designation: "76th DShD (RuAF)",
    faction: "RUSSIA",
    theater: "EASTERN_EUROPE",
    unitType: "AIRBORNE",
    icon: "🦅",
    lat: 51.28,
    lon: 35.38,
    personnelStrength: 8500,
    combatReadinessPct: 78,
    commander: "Maj. Gen. Denis Shishov",
    equipment: ["BMD-4M", "BTR-MDM Rakushka", "T-72B3M", "2S9 Nona"],
    casualtyEstimate: 3400,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Kursk Border Interception Zone",
    correlatedAssets: ["RUB=X", "BRENT"],
  },
  {
    id: "unit-006",
    name: "58th Combined Arms Army (Southern Military District)",
    designation: "58th CAA (RuAF)",
    faction: "RUSSIA",
    theater: "EASTERN_EUROPE",
    unitType: "ARMOR",
    icon: "🛡️",
    lat: 47.45,
    lon: 35.85,
    personnelStrength: 18000,
    combatReadinessPct: 75,
    commander: "Lt. Gen. Denis Lyamin",
    equipment: ["T-90M Proryv", "BMP-3", "TOS-1A Solntsepyok", "Iskander-M"],
    casualtyEstimate: 6200,
    status: "FORTIFIED",
    frontlineSector: "Zaporizhzhia Surovikin Line (Robotyne–Tokmak)",
    correlatedAssets: ["ELECTRICITY_EU", "URANIUM"],
  },
  {
    id: "unit-007",
    name: "155th Separate Guards Naval Infantry Brigade",
    designation: "155th OBrMP (Pacific Fleet)",
    faction: "RUSSIA",
    theater: "EASTERN_EUROPE",
    unitType: "INFANTRY",
    icon: "⚓",
    lat: 47.78,
    lon: 37.25,
    personnelStrength: 3200,
    combatReadinessPct: 70,
    commander: "Col. Mikhail Gudkov",
    equipment: ["T-80BVM", "BMP-2M Berezhok", "Uragan MLRS"],
    casualtyEstimate: 2100,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Vuhledar Assault Sector",
    correlatedAssets: ["STEEL", "COAL"],
  },
  {
    id: "unit-008",
    name: "114th Separate Motorized Rifle Brigade",
    designation: "114th OMSBr (1st Army Corps)",
    faction: "RUSSIA",
    theater: "EASTERN_EUROPE",
    unitType: "MECHANIZED",
    icon: "🚜",
    lat: 48.22,
    lon: 37.40,
    personnelStrength: 3900,
    combatReadinessPct: 80,
    commander: "Col. Roman Vorobyov",
    equipment: ["T-72B", "BMP-1AM Basurmanin", "Lancet Drone Teams"],
    casualtyEstimate: 1450,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Avdiivka–Ocheretyne Breakout",
    correlatedAssets: ["EUR/USD"],
  },
  {
    id: "unit-009",
    name: "Magyar Birds Strike Drone Battalion",
    designation: "414th Separate UAV Strike Reg.",
    faction: "UKRAINE",
    theater: "EASTERN_EUROPE",
    unitType: "DRONE_SWARM",
    icon: "🛸",
    lat: 48.35,
    lon: 37.22,
    personnelStrength: 1200,
    combatReadinessPct: 96,
    commander: "Robert 'Magyar' Brovdi",
    equipment: ["FPV Kamikaze Drones", "Vampire Heavy Bombers", "EW Interceptors"],
    casualtyEstimate: 85,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Donbas Strategic Interdiction Sector",
    correlatedAssets: ["TECH_SEMIS"],
  },
  {
    id: "unit-010",
    name: "Rubikon Advanced Drone Warfare Center",
    designation: "MoD Testing & Drone Strike Wing",
    faction: "RUSSIA",
    theater: "EASTERN_EUROPE",
    unitType: "DRONE_SWARM",
    icon: "🛸",
    lat: 51.35,
    lon: 35.60,
    personnelStrength: 850,
    combatReadinessPct: 94,
    commander: "Col. Alexey Morozov",
    equipment: ["Fiber-Optic Guided FPV Drones", "ZALA 421-16E", "Lancet-3"],
    casualtyEstimate: 45,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Kursk High-Precision Drone Hunting Zone",
    correlatedAssets: ["ELECTRONICS_FUTURES"],
  },

  // ── MIDDLE EAST & LEVANT THEATER (ISRAEL - LEBANON - GAZA) ──
  {
    id: "unit-011",
    name: "98th Paratroopers Division 'Ha-Esh'",
    designation: "98th Div (IDF Northern Command)",
    faction: "ISRAEL",
    theater: "MIDDLE_EAST",
    unitType: "AIRBORNE",
    icon: "🦅",
    lat: 33.26,
    lon: 35.48,
    personnelStrength: 12000,
    combatReadinessPct: 92,
    commander: "Brig. Gen. Guy Levy",
    equipment: ["Merkava Mk 4M Windbreaker", "Namer APC", "Spike NLOS"],
    casualtyEstimate: 310,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Southern Lebanon Border Incursion Axis",
    correlatedAssets: ["CL=F (Crude)", "GC=F (Gold)", "TA35"],
  },
  {
    id: "unit-012",
    name: "36th Armored Division 'Ga'ash'",
    designation: "36th Div (IDF)",
    faction: "ISRAEL",
    theater: "MIDDLE_EAST",
    unitType: "ARMOR",
    icon: "🛡️",
    lat: 33.15,
    lon: 35.32,
    personnelStrength: 14500,
    combatReadinessPct: 90,
    commander: "Brig. Gen. Dado Bar-Kalifa",
    equipment: ["Merkava Mk 4 Barak", "Eitan AFV", "M109 Doher 155mm"],
    casualtyEstimate: 420,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Central Sector (Maroun el-Ras–Bint Jbeil)",
    correlatedAssets: ["BRENT", "USD/ILS"],
  },
  {
    id: "unit-013",
    name: "Hezbollah Radwan Special Operations Forces",
    designation: "Unit 125 (Radwan Command)",
    faction: "HEZBOLLAH",
    theater: "MIDDLE_EAST",
    unitType: "SPECIAL_FORCES",
    icon: "⚔️",
    lat: 33.32,
    lon: 35.42,
    personnelStrength: 6500,
    combatReadinessPct: 74,
    commander: "Ali Reda Hajj Hassan (Council)",
    equipment: ["Kornet-EM Anti-Tank", "Almas-3 TV-Guided ATGM", "Underground Tunnels"],
    casualtyEstimate: 1100,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Litani River South Mountain Redoubt",
    correlatedAssets: ["CL=F", "NATURAL_GAS_MED"],
  },
  {
    id: "unit-014",
    name: "Hezbollah Precision Rocket & Missile Unit",
    designation: "Strategic Missile Division",
    faction: "HEZBOLLAH",
    theater: "MIDDLE_EAST",
    unitType: "ARTILLERY_MISSILE",
    icon: "🚀",
    lat: 33.85,
    lon: 35.90,
    personnelStrength: 4000,
    combatReadinessPct: 81,
    commander: "Hajj Mohammad Tabatabai",
    equipment: ["Fateh-110", "Khaibar-1", "Qader-1 Ballistic Missile", "Fadi-4"],
    casualtyEstimate: 290,
    status: "STRIKE_ALERT",
    frontlineSector: "Bekaa Valley Launch Corridor",
    correlatedAssets: ["GOLD", "OIL_VOLATILITY"],
  },
  {
    id: "unit-015",
    name: "162nd Armored Division 'Steel Formation'",
    designation: "162nd Div (IDF Southern Command)",
    faction: "ISRAEL",
    theater: "MIDDLE_EAST",
    unitType: "ARMOR",
    icon: "🛡️",
    lat: 31.35,
    lon: 34.28,
    personnelStrength: 9500,
    combatReadinessPct: 86,
    commander: "Brig. Gen. Itzik Cohen",
    equipment: ["Merkava Mk 4", "D9R Armored Bulldozers", "Iron Fist Active Protection"],
    casualtyEstimate: 540,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Jabalia & Northern Gaza Sector",
    correlatedAssets: ["TA35", "ILS=X"],
  },

  // ── RED SEA & BAB EL-MANDEB THEATER ──
  {
    id: "unit-016",
    name: "Carrier Strike Group 9 (USS Theodore Roosevelt CSG)",
    designation: "CSG-9 / Task Force 50 (US Navy)",
    faction: "US_COALITION",
    theater: "RED_SEA",
    unitType: "NAVAL_TASK_FORCE",
    icon: "🚢",
    lat: 13.80,
    lon: 48.50,
    personnelStrength: 6500,
    combatReadinessPct: 98,
    commander: "Rear Adm. Christopher Alexander",
    equipment: ["CVN-71 Aircraft Carrier", "F/A-18E/F Super Hornet", "CG-71 USS Cape St. George", "DDG-114"],
    casualtyEstimate: 0,
    status: "STRIKE_ALERT",
    frontlineSector: "Gulf of Aden & Arabian Sea Air Shield",
    correlatedAssets: ["BRENT", "MAERSK.DK", "BALTIC_DRY"],
  },
  {
    id: "unit-017",
    name: "Combined Task Force 153 (Red Sea Maritime Security)",
    designation: "CTF-153 (Operation Prosperity Guardian)",
    faction: "US_COALITION",
    theater: "RED_SEA",
    unitType: "NAVAL_TASK_FORCE",
    icon: "🚢",
    lat: 12.65,
    lon: 43.40,
    personnelStrength: 2800,
    combatReadinessPct: 95,
    commander: "Capt. Sean Bailey",
    equipment: ["Arleigh Burke DDGs", "HMS Diamond (Type 45)", "SM-2 / SM-6 Interceptors"],
    casualtyEstimate: 0,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Bab el-Mandeb Chokepoint Transit Guard",
    correlatedAssets: ["CONTAINER_FREIGHT", "BDI"],
  },
  {
    id: "unit-018",
    name: "Ansar Allah 5th Coastal Defense Naval & Missile Brigade",
    designation: "Houthi Coastal Defense Force",
    faction: "HOUTHI",
    theater: "RED_SEA",
    unitType: "ARTILLERY_MISSILE",
    icon: "🚀",
    lat: 14.80,
    lon: 42.95,
    personnelStrength: 3500,
    combatReadinessPct: 88,
    commander: "Maj. Gen. Muhammad al-Ghamari",
    equipment: ["Palestine-2 Hypersonic ASBM", "Toufan-1 Explosive USVs", "Samad-3 UAVs", "Quds-4 Cruise"],
    casualtyEstimate: 410,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Hodeidah & Al-Salif Coastal Battery",
    correlatedAssets: ["BZ=F", "INSURANCE_MARINE"],
  },

  // ── INDO-PACIFIC & TAIWAN STRAIT THEATER ──
  {
    id: "unit-019",
    name: "PLA Eastern Theater Command 73rd Group Army",
    designation: "73rd Group Army (Amphibious Core)",
    faction: "CHINA",
    theater: "INDO_PACIFIC",
    unitType: "MECHANIZED",
    icon: "🚜",
    lat: 24.50,
    lon: 118.10,
    personnelStrength: 45000,
    combatReadinessPct: 96,
    commander: "Lt. Gen. Hu Zhongqiang",
    equipment: ["Type 05 Amphibious AFV", "Type 99A MBT", "PHL-16 370mm MLRS", "Y-20 Air Transport"],
    casualtyEstimate: 0,
    status: "STRIKE_ALERT",
    frontlineSector: "Xiamen & Taiwan Strait Amphibious Staging",
    correlatedAssets: ["TSM", "SOXX", "USD/TWD", "FXI"],
  },
  {
    id: "unit-020",
    name: "ROCM 66th Marine Brigade 'Iron Fist'",
    designation: "66th Marine Bde (Taiwan)",
    faction: "TAIWAN",
    theater: "INDO_PACIFIC",
    unitType: "SPECIAL_FORCES",
    icon: "🛡️",
    lat: 25.02,
    lon: 121.45,
    personnelStrength: 6000,
    combatReadinessPct: 92,
    commander: "Maj. Gen. Chen Chun-chi",
    equipment: ["AAV-7A1 RAM/RS", "Hsiung Feng III Anti-Ship", "Tien-Kung III SAM", "Javelin"],
    casualtyEstimate: 0,
    status: "FORTIFIED",
    frontlineSector: "Taipei Defense & Linkou Beach Bastion",
    correlatedAssets: ["TSM", "HSTECH", "NIKKEI"],
  },

  // ── SUDAN & SAHEL THEATER ──
  {
    id: "unit-021",
    name: "Rapid Support Forces (RSF 1st Mobile Strike Column)",
    designation: "RSF Central Command",
    faction: "SUDAN_RSF",
    theater: "AFRICA",
    unitType: "INFANTRY",
    icon: "⚔️",
    lat: 15.55,
    lon: 32.52,
    personnelStrength: 16000,
    combatReadinessPct: 76,
    commander: "Gen. Mohamed Hamdan Dagalo (Hemedti)",
    equipment: ["Technicals (Mounted 23mm/14.5mm)", "BTR-70", "Kornet ATGM", "Kamikaze Drones"],
    casualtyEstimate: 6800,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "Khartoum City Siege & Blue Nile Bridges",
    correlatedAssets: ["GC.US (Gold)", "OIL_ARABIC"],
  },
  {
    id: "unit-022",
    name: "SAF Special Action Forces (General Intelligence Directorate)",
    designation: "SAF 6th Infantry Div & Special Task",
    faction: "SUDAN_SAF",
    theater: "AFRICA",
    unitType: "SPECIAL_FORCES",
    icon: "🛡️",
    lat: 13.62,
    lon: 25.35,
    personnelStrength: 9000,
    combatReadinessPct: 69,
    commander: "Gen. Abdel Fattah al-Burhan Command",
    equipment: ["Al-Zubair 2 MBT", "Mi-24 Hind Gunships", "Mohajer-6 UCAVs", "122mm D-30"],
    casualtyEstimate: 5100,
    status: "ACTIVE_ENGAGED",
    frontlineSector: "El Fasher (North Darfur Defense Bastion)",
    correlatedAssets: ["GOLD_MINING", "COMMODITIES"],
  },
];

// Generate synthetic records up to 136 units to represent full tactical matrix
(function populateFull136ORBAT() {
  const existingCount = ACTIVE_136_MILITARY_UNITS.length;
  const targetCount = 136;
  const sectors = [
    { name: "Kupiansk–Svatove Sector", lat: 49.7, lon: 37.8, faction: "UKRAINE", theater: "EASTERN_EUROPE", type: "MECHANIZED", icon: "🚜" },
    { name: "Siversk Salient", lat: 48.86, lon: 38.08, faction: "RUSSIA", theater: "EASTERN_EUROPE", type: "ARTILLERY_MISSILE", icon: "🚀" },
    { name: "Krasnohorivka–Marinka Sector", lat: 47.98, lon: 37.52, faction: "RUSSIA", theater: "EASTERN_EUROPE", type: "ARMOR", icon: "🛡️" },
    { name: "Dnipro Delta & Krynky Sector", lat: 46.72, lon: 33.10, faction: "UKRAINE", theater: "EASTERN_EUROPE", type: "SPECIAL_FORCES", icon: "⚔️" },
    { name: "Golan Heights / Mount Hermon", lat: 33.30, lon: 35.80, faction: "ISRAEL", theater: "MIDDLE_EAST", type: "AIR_DEFENSE", icon: "🎯" },
    { name: "Al-Bukamal Syria-Iraq Border", lat: 34.45, lon: 40.92, faction: "REGIONAL", theater: "MIDDLE_EAST", type: "DRONE_SWARM", icon: "🛸" },
    { name: "Saada Highland SAM Network", lat: 16.95, lon: 43.75, faction: "HOUTHI", theater: "RED_SEA", type: "AIR_DEFENSE", icon: "🎯" },
    { name: "Penghu Islands Fortress Command", lat: 23.57, lon: 119.58, faction: "TAIWAN", theater: "INDO_PACIFIC", type: "ARTILLERY_MISSILE", icon: "🚀" },
    { name: "Mali–Burkina Faso Border Zone", lat: 14.20, lon: -1.50, faction: "SAHEL_ALLIANCE", theater: "AFRICA", type: "INFANTRY", icon: "⚔️" },
  ];

  for (let i = existingCount + 1; i <= targetCount; i++) {
    const sec = sectors[(i - 1) % sectors.length];
    const jitterLat = sec.lat + (Math.sin(i * 1.7) * 0.4);
    const jitterLon = sec.lon + (Math.cos(i * 2.3) * 0.4);

    ACTIVE_136_MILITARY_UNITS.push({
      id: `unit-${String(i).padStart(3, "0")}`,
      name: `Battlegroup ${i} (${sec.name.split(" ")[0]} Tactical Reg.)`,
      designation: `BTG-${i} [${sec.faction}]`,
      faction: sec.faction as any,
      theater: sec.theater as any,
      unitType: sec.type as any,
      icon: sec.icon,
      lat: Math.round(jitterLat * 100) / 100,
      lon: Math.round(jitterLon * 100) / 100,
      personnelStrength: Math.floor(1800 + Math.random() * 3500),
      combatReadinessPct: Math.floor(68 + Math.random() * 28),
      commander: `Brig. Cmdr. Sector Staff-${i}`,
      equipment: ["Modernized AFV/MBT", "EW Intercept Jammer", "Heavy Mortars 120mm"],
      casualtyEstimate: Math.floor(200 + Math.random() * 1200),
      status: i % 3 === 0 ? "ACTIVE_ENGAGED" : i % 3 === 1 ? "FORTIFIED" : "STRIKE_ALERT",
      frontlineSector: sec.name,
      correlatedAssets: ["DEFENSE_ETF", "COMMODITIES"],
    });
  }
})();

/* ─────────────────────────────────────────────────────────────────────────────
   TACTICAL FRONTLINE VECTORS (FLOT / CONTACT LINES)
   ───────────────────────────────────────────────────────────────────────────── */
export const TACTICAL_FRONTLINES: FrontlineBoundary[] = [
  {
    id: "flot-donbas",
    name: "Donbas Strategic Contact Line (Pokrovsk–Toretsk–Chasiv Yar)",
    theater: "EASTERN_EUROPE",
    color: "#ef4444",
    points: [
      [49.8, 38.0], [49.2, 38.2], [48.86, 37.75], [48.59, 37.89],
      [48.28, 37.18], [47.98, 37.52], [47.78, 37.25], [47.45, 35.85]
    ],
  },
  {
    id: "flot-kursk-salient",
    name: "Kursk Border Salient Perimeter",
    theater: "EASTERN_EUROPE",
    color: "#38bdf8",
    points: [
      [51.40, 34.90], [51.35, 35.20], [51.20, 35.27], [51.15, 35.50], [51.30, 35.70], [51.45, 35.40]
    ],
  },
  {
    id: "flot-blue-line",
    name: "UN Blue Line (Lebanon–Israel Border Demarcation)",
    theater: "MIDDLE_EAST",
    color: "#eab308",
    points: [
      [33.09, 35.10], [33.12, 35.25], [33.20, 35.40], [33.26, 35.58], [33.30, 35.80]
    ],
  },
];
